FROM python:3.11


WORKDIR /app

COPY pyfiles requirements.txt /app/
#RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt


EXPOSE 11434

RUN apt-get update && \
    apt-get install -y \
    curl \
    vim \
    jq

RUN mkdir /app/data
RUN mkdir /app/data/jobyamls

COPY data /app/data 
COPY scripts /app
RUN chmod +x /app/inotify-install.sh
RUN /app/inotify-install.sh
RUN chmod +x /app/makejobs.sh

ENV SLACK_BOT_TOKEN=''
ENV SLACK_APP_TOKEN=''
ENV SAGE_USERNAME=''
ENV SAGE_USERTOKEN=''

############## FOR SESCTL #######################
# Set environment variables
ENV SES_HOST=https://es.sagecontinuum.org
ENV SES_USER_TOKEN=''

# Download the file, rename it, and place it in PATH
RUN curl -L -o /usr/local/bin/sesctl https://github.com/waggle-sensor/edge-scheduler/releases/download/0.26.0/sesctl-linux-amd64 && \
    chmod +x /usr/local/bin/sesctl

# Ensure /usr/local/bin is in PATH (it usually is by default)
ENV PATH="/usr/local/bin:${PATH}"
##################################################


